// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADne0Vd11Gf9K_IiDUf68TAf2lcMWe8AY',
    appId: '1:508850397000:web:342f30e39741c6988add7d',
    messagingSenderId: '508850397000',
    projectId: 'efrei092023m2gr1',
    authDomain: 'efrei092023m2gr1.firebaseapp.com',
    storageBucket: 'efrei092023m2gr1.appspot.com',
    measurementId: 'G-PKDL2EVBVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdenLCZsIpTsPQ5DBRZWrUZZOwwkSeMTE',
    appId: '1:508850397000:android:81ab8d0e1b91b8a08add7d',
    messagingSenderId: '508850397000',
    projectId: 'efrei092023m2gr1',
    storageBucket: 'efrei092023m2gr1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg5OORxFVmjzCn0neH7MhBMj37b3m-xMc',
    appId: '1:508850397000:ios:c7b221a9b730dfb08add7d',
    messagingSenderId: '508850397000',
    projectId: 'efrei092023m2gr1',
    storageBucket: 'efrei092023m2gr1.appspot.com',
    iosBundleId: 'com.example.eferei2023gr109',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg5OORxFVmjzCn0neH7MhBMj37b3m-xMc',
    appId: '1:508850397000:ios:b7352f942b4f6de28add7d',
    messagingSenderId: '508850397000',
    projectId: 'efrei092023m2gr1',
    storageBucket: 'efrei092023m2gr1.appspot.com',
    iosBundleId: 'com.example.eferei2023gr109.RunnerTests',
  );
}
